sudo: false
language: php
dist: trusty
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - XDEBUG_MODE=coverage
script:
  - composer install
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
